config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/auth/oauth/callback', to: 'sessions#create'


  resources :appliance_comments
  resources :appliances, only: %i[show new edit create update destroy]
  resources :kitchens
  resources :users, except: %i[new create destroy]

  post 'appliances/:id/', to: 'appliances#fire_transition', as: :fire_transition

  root 'kitchens#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appliance.rb
class Appliance < ApplicationRecord
  belongs_to :kitchen
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :appliance_comments

  alias_attribute :comments, :appliance_comments

  enum category: %i[basic extra]
  enum status: %i[operational broken damaged]

  include ApplianceStateMachine

  def self.actions
    Appliance.aasm.events.map(&:name)
  end

  def valid_actions
    Appliance.actions.select { |e| send("may_#{e}?") }
  end

  def valid_action?(transition)
    valid_actions.include? transition
  end

  def fire_transition(transition)
    begin
      send((transition + '!').to_sym) if valid_action?(transition.to_sym)
    rescue AASM::InvalidTransition
      errors.add(:category, :invalid)

      raise ActiveRecord::RecordInvalid
    end
  end
end

app/controllers/appliances_controller.rb
class AppliancesController < ApplicationController
  before_action :set_appliance, only: [:show, :edit, :update, :destroy, :fire_transition]
  before_action :set_kitchens, only: [:new, :edit, :update]

  # GET /appliances/1
  # GET /appliances/1.json
  def show
    @new_appliance_comment = ApplianceComment.new(appliance: @appliance)
  end

  # GET /appliances/new
  def new
    @appliance = Appliance.new(params.permit(:kitchen_id))
    authorize @appliance
  end

  # GET /appliances/1/edit
  def edit
    authorize @appliance
  end

  # POST /appliances
  # POST /appliances.json
  def create
    @appliance = Appliance.new(appliance_params)
    @appliance.owner = current_user
    authorize @appliance
    respond_to do |format|
      if @appliance.save
        format.html { redirect_to @appliance, notice: 'Appliance was successfully created.' }
        format.json { render :show, status: :created, location: @appliance }
      else
        format.html { render :new }
        format.json { render json: @appliance.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /appliances/1
  # PATCH/PUT /appliances/1.json
  def update
    authorize @appliance
    respond_to do |format|
      if @appliance.update(appliance_params)
        @appliance.fire_transition(params[:transanction]) unless params[:transanction].nil?
        format.html { redirect_to @appliance, notice: 'Appliance was successfully updated.' }
        format.json { render :show, status: :ok, location: @appliance }
      else
        format.html { render :edit }
        format.json { render json: @appliance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appliances/1
  # DELETE /appliances/1.json
  def destroy
    authorize @appliance
    @appliance.destroy
    respond_to do |format|
      format.html { redirect_to appliances_url, notice: 'Appliance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fire_transition
    @appliance.fire_transition(params[:transition])
    redirect_to appliance_path @appliance
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appliance
      @appliance = Appliance.includes(appliance_comments:[:owner]).find(params[:id])
    end

    def set_kitchens
      @kitchens = Kitchen.all
    end

    # Only allow a list of trusted parameters through.
    def appliance_params
      params.require(:appliance).permit(:name, :category, :status, :description, :kitchen_id)
    end
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/views/appliances/_form.html.haml
= form_for appliance do |f|
  - if appliance.errors.any?
    = render 'layouts/errors', errors: appliance.errors

  .mt-4
    = f.label :name, "Elnevezése", class: "block text-gray-700 text-sm font-bold mb-2"
    = f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
  .mt-1
    = f.label :category, "Típusa", class: "block text-gray-700 text-sm font-bold mb-2"
    .relative
      = f.select :category, options_for_select(Appliance.categories.map {|k, v| [k, k]}), {}, class: "block shadow bg-white appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
      .pointer-events-none.absolute.inset-y-0.right-0.flex.items-center.px-2.text-gray-700
        %svg.fill-current.h-4.w-4{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"}
  .mt-1
    = f.label :status, "Állapota", class: "block text-gray-700 text-sm font-bold mb-2"
    .relative
      = f.select :status, options_for_select(Appliance.statuses.map {|k, v| [k, k]}), {}, class: "block shadow bg-white appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
      .pointer-events-none.absolute.inset-y-0.right-0.flex.items-center.px-2.text-gray-700
        %svg.fill-current.h-4.w-4{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"}
  .mt-1
    = f.label :description, "Leírás", class: "block text-gray-700 text-sm font-bold mb-2"
    = f.text_area :description, rows: 3, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
  .mt-1
    = f.label :kitchen_id, "Konyha szintje", class: "block text-gray-700 text-sm font-bold mb-2"
    .relative
      = f.select :kitchen_id, kitchens.collect {|k| [k.floor, k.id]}, {}, class: "block shadow bg-white appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
      .pointer-events-none.absolute.inset-y-0.right-0.flex.items-center.px-2.text-gray-700
        %svg.fill-current.h-4.w-4{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"}
  .mt-1
    = f.submit "Mentés", class: "bg-green-600 hover:bg-green-500 text-white font-bold py-2 px-4 rounded"
    = yield :extra_buttons

app/views/appliances/_status_transition.html.haml
= form_with url: fire_transition_url do |f|
  .mt-4.bg-white.rounded-lg.p-3.md:p-8.shadow-lg.hover:shadow-2xl.transition-all.duration-150
    %h3.text-xl.font-bold Esemény rögzítése

    - if appliance.errors.any?
      = render 'layouts/errors', errors: appliance.errors
    .relative
      = f.select :transition, appliance.valid_actions.map{|a| [t(a) , a]},{},class: "block shadow bg-white appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
      .pointer-events-none.absolute.inset-y-0.right-0.flex.items-center.px-2.text-gray-700
        %svg.fill-current.h-4.w-4{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
          %path{:d => "M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"}
    .grid.grid-cols-4
      .col-span-4.md:col-span-3

      .col-span-4.md:col-span-1
        .mt-1
          = f.hidden_field(:appliance_id ,value: appliance.id)
        .mt-2.text-right
          = f.submit 'Frissítés', class: "bg-green-600 hover:bg-green-500 text-white font-bold py-2 px-4 rounded col-span-1"

app/views/appliances/edit.html.haml
- content_for :extra_buttons do
  = link_to 'Eltávolítás', @appliance, type: :button, method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-600 hover:bg-red-500 text-white font-bold py-2 px-4 rounded float-right"

%h1.text-xl.md:text-2xl Eszköz szerkesztése
= render 'form', {appliance: @appliance, kitchens: @kitchens}
.mt-12
  = link_to 'Vissza', @appliance, class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"

app/views/appliances/new.html.haml
%h1.text-xl.md:text-2xl Új eszköz
= render 'form', {appliance: @appliance, kitchens: @kitchens}
.mt-12
  = link_to 'Vissza', @appliance, class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"

app/views/appliances/show.html.haml
%h2.text-2xl.md:text-4xl.w-full
  %strong Eszköz

.mt-4.bg-white.rounded-lg
  .p-4.grid.grid-cols-2
    %strong.col-span-2.md:col-span-1.p-1.md:p-2.md:border-b.md:border-gray-300
      Elnevezés
    .col-span-2.md:col-span-1.p-1.md:p-2.border-b.border-gray-300
      = @appliance.name
    %strong.col-span-1.p-1.md:p-2.border-b.border-gray-300
      Típusa
    .col-span-1.p-1.md:p-2.border-b.border-gray-300
      = @appliance.category
    %strong.col-span-1.p-1.md:p-2.border-b.border-gray-300
      Állapota
    .col-span-1.p-1.md:p-2.border-b.border-gray-300
      - if @appliance.status == "broken"
        .text-red-500= t @appliance.status
      - else
        .text-green-500= t @appliance.status
    %strong.col-span-1.p-1.md:p-2.border-b.border-gray-300
      Konyha:
    .col-span-1.p-1.md:p-2.border-b.border-gray-300
      = "#{@appliance.kitchen.floor}. szint"
    %strong.col-span-2.md:col-span-1.p-1.md:p-2.border-b.border-gray-300
      Leírás
    .col-span-2.md:col-span-1.p-1.md:p-2.border-b.border-gray-300
      = @appliance.description
    %strong.col-span-2.md:col-span-1.p-1.md:p-2
      Tulajdonos
    .col-span-2.md:col-span-1.p-1.md:p-2.text-blue-600
      = link_to @appliance.owner.name, user_path(@appliance.owner), class: "hover:underline"
= render "status_transition", appliance: @appliance

%body.bg-gray-200.flex.items-center.justify-center.h-screen
%button.modal-open.my-10.shadow.bg-blue-500.hover:bg-blue-600.focus:shadow-outline.focus:outline-none.text-white.font-bold.py-2.px-4.rounded Jelentés hozzaadasa

.my-4.flex.flex-wrap
  .flex-1.my-2
    = link_to 'Vissza', kitchen_path(@appliance.kitchen), class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"
  .flex-1.text-right.my-2
    = link_to 'Módosítás', edit_appliance_path(@appliance), class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"

- unless @appliance.comments.empty?
  .my-4.text-xl.md:text-2xl
    Jelentések:

- @appliance.comments.reverse.each do |comment|
  .transition-all.duration-150.px-2.py-2
    .flex.flex-col.items-stretch.min-h-full.pb-4.mb-1.transition-all.duration-150.bg-white.rounded-lg.shadow.hover:shadow-lg
      .grid.grid-cols-3.px-3.py-2
        - color = "text-green-500" if comment.category == "fix"
        - color = "text-red-500" if comment.category == "problem"
        .col-span-1.text-sm.uppercase.font-bold.py-1{class: "#{color}"}
          = t comment.category
        .col-span-2.md:grid.md:grid-cols-2.py-1
          .text-sm.text-right.md:text-center
            = l comment.created_at, format: :short
          .text-sm.font-medium.text-blue-600.text-right
            = link_to comment.owner.name, user_path(comment.owner), class: "hover:underline"
      %hr.border-gray-30
      = link_to appliance_comment_path(comment) do
        %p.flex.flex-row.flex-wrap.w-full.px-5.py-2.text-sm.text-justify
          = comment.body


%link{:href => "https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css", :rel => "stylesheet"}/
:css
  .modal {
    transition: opacity 0.25s ease;
  }
  body.modal-active {
    overflow-x: hidden;
    overflow-y: visible !important;
  }


/ Modal
.modal.opacity-0.pointer-events-none.fixed.w-full.h-full.top-0.left-0.flex.items-center.justify-center
  .modal-overlay.absolute.w-full.h-full.bg-gray-900.opacity-50
  .modal-container.bg-white.md:max-w-md.mx-10.rounded.shadow-lg.z-50.overflow-y-auto{:class => "w-10/12"}
    .modal-close.absolute.top-0.right-0.cursor-pointer.flex.flex-col.items-center.mt-4.mr-4.text-white.text-sm.z-50
      %svg.fill-current.text-white{:height => "18", :viewbox => "0 0 18 18", :width => "18", :xmlns => "http://www.w3.org/2000/svg"}
        %path{:d => "M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"}
      %span.text-sm (Esc)
    / Add margin if you want to see some of the overlay behind the modal
    .modal-content.py-4.text-left.px-6
      / Title
     
      .title
        %h2.text-center-3xl.font-semibold.text-gray-800.md:text-4xl
          Segits a szintet
          %span.text-orange-400 uptodate
          %span.text-3xl.font-semibold.text-gray-800.md:text-4xl tartani
        %h2.text-xl.md:text-xl.w-full
          %strong Tolts fel egy uj jelentest 
          %span.text-xs.font-semibold.inline-block.py-1.px-2.uppercase.rounded-full.text-orange-600.bg-orange-200.uppercase.last:mr-0.mr-1 NEW
      
      .form.mt-4
        .flex.flex-col.text-sm
        .w-full.mt-8
          = render 'appliance_comments/compact_form', appliance_comment: @new_appliance_comment

      / Footer
      .flex.justify-end.pt-2
        %button.modal-close.px-4.bg-blue-600.p-3.rounded-lg.text-white.hover:bg-blue-500 Close
  :javascript
    var openmodal = document.querySelectorAll('.modal-open')
    for (var i = 0; i < openmodal.length; i++) {
      openmodal[i].addEventListener('click', function(event){
      event.preventDefault()
      toggleModal()
      })
    }
    
    const overlay = document.querySelector('.modal-overlay')
    overlay.addEventListener('click', toggleModal)
    
    var closemodal = document.querySelectorAll('.modal-close')
    for (var i = 0; i < closemodal.length; i++) {
      closemodal[i].addEventListener('click', toggleModal)
    }
    
    document.onkeydown = function(evt) {
      evt = evt || window.event
      var isEscape = false
      if ("key" in evt) {
      isEscape = (evt.key === "Escape" || evt.key === "Esc")
      } else {
      isEscape = (evt.keyCode === 27)
      }
      if (isEscape && document.body.classList.contains('modal-active')) {
      toggleModal()
      }
    };
    
    
    function toggleModal () {
      const body = document.querySelector('body')
      const modal = document.querySelector('.modal')
      modal.classList.toggle('opacity-0')
      modal.classList.toggle('pointer-events-none')
      body.classList.toggle('modal-active')
    }