config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/auth/oauth/callback', to: 'sessions#create'


  resources :appliance_comments
  resources :appliances, only: %i[show new edit create update destroy]
  resources :kitchens
  resources :users, except: %i[new create destroy]

  post 'appliances/:id/', to: 'appliances#fire_transition', as: :fire_transition

  root 'kitchens#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/kitchen.rb
class Kitchen < ApplicationRecord
  has_many :appliances
  has_many :kitchen_assignments
  has_many :kitchen_admins, through: :kitchen_assignments, source: :user

  validates :floor, uniqueness: true
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  before_action :set_kitchen, only: [:show, :edit, :update, :destroy]

  # GET /kitchens
  # GET /kitchens.json
  def index
    @kitchens = Kitchen.all.sort_by(&:floor)
  end

  # GET /kitchens/1
  # GET /kitchens/1.json
  def show
  end

  # GET /kitchens/new
  def new
    @kitchen = Kitchen.new
    authorize @kitchen
  end

  # GET /kitchens/1/edit
  def edit
    authorize @kitchen
  end

  # POST /kitchens
  # POST /kitchens.json
  def create
    @kitchen = Kitchen.new(kitchen_params)
    authorize @kitchen
    respond_to do |format|
      if @kitchen.save
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully created.' }
        format.json { render :show, status: :created, location: @kitchen }
      else
        format.html { render :new }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kitchens/1
  # PATCH/PUT /kitchens/1.json
  def update
    authorize @kitchen
    respond_to do |format|
      if @kitchen.update(kitchen_params)
        format.html { redirect_to @kitchen, notice: 'Kitchen was successfully updated.' }
        format.json { render :show, status: :ok, location: @kitchen }
      else
        format.html { render :edit }
        format.json { render json: @kitchen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kitchens/1
  # DELETE /kitchens/1.json
  def destroy
    authorize @kitchen
    @kitchen.destroy
    respond_to do |format|
      format.html { redirect_to kitchens_url, notice: 'Kitchen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kitchen
      @kitchen = Kitchen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kitchen_params
      params.require(:kitchen).permit(:floor)
    end
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/views/kitchens/_form.html.haml
= form_with(model: kitchen, local: true) do |form|
  - if kitchen.errors.any?
    = render 'layouts/errors', errors: kitchen.errors

  .mt-4
    = form.label :floor, "Szint", class: "block text-gray-700 text-sm font-bold mb-2"
    = form.number_field :floor, max: 18, min: 3, required: true, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
  .mt-1
    = form.submit "Mentés", class: "bg-green-600 hover:bg-green-500 text-white font-bold py-2 px-4 rounded"
    = yield :extra_buttons

app/views/kitchens/edit.html.haml
- content_for :extra_buttons do
  = link_to 'Eltávolítás', @kitchen, type: :button, method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-600 hover:bg-red-500 text-white font-bold py-2 px-4 rounded float-right"

%h1.text-xl.md:text-2xl Konyha szerkesztése
= render 'form', kitchen: @kitchen
.mt-12
  = link_to 'Vissza', @kitchen, class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"

app/views/kitchens/index.html.haml
%h1.text-3xl.md:text-5xl.pb-8
  Konyhák

.grid.grid-cols-1.md:grid-cols-2.md:gap-4.mb-8
  - @kitchens.each do |kitchen|
    = link_to kitchen, class: "p-4 mb-1 bg-white hover:bg-gray-100 shadow-lg rounded-lg cursor-pointer" do
      %span.text-xl
        = "#{kitchen.floor}. szint"
      %span.p-1.float-right
        %svg.w-5.h-5{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24"}
          %path{:d => "M13.25,10L6.109,2.58c-0.268-0.27-0.268-0.707,0-0.979c0.268-0.27,0.701-0.27,0.969,0l7.83,7.908  c0.268,0.271,0.268,0.709,0,0.979l-7.83,7.908c-0.268,0.271-0.701,0.27-0.969,0c-0.268-0.269-0.268-0.707,0-0.979L13.25,10z"}

app/views/kitchens/new.html.haml
%h1.text-xl.md:text-2xl Új konyha
= render 'form', kitchen: @kitchen
.mt-12
  = link_to 'Vissza', kitchens_path, class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"

app/views/kitchens/show.html.haml
.flex.flex-wrap
  .flex-none.pr-2
    %h2.text-2xl.md:text-4xl.w-full
      %strong= "#{@kitchen.floor}. szinti konyha"
  .flex-auto.mb-4
    .text-right.py-2
      = link_to 'Módosítás', edit_kitchen_path(@kitchen), class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"

.mb-4.text-lg.md:text-xl
  A szint eszközei:

.w-full
  - @kitchen.appliances.each do |appliance|
    - color = appliance.status == "operational" ? "green" : "red"
    = link_to appliance, class: "flex flex-wrap items-center cursor-pointer my-1 text-white shadow hover:bg-"+color+"-500 bg-"+color+"-600 rounded " do
      .flex-auto.p-3.break-words
        %span.md:text-lg
          %strong
            = appliance.name
        - if appliance.category == "extra"
          %span.text-xs.font-medium.bg-yellow-200.text-gray-800.py-1.px-2.rounded.align-top
            extra!
      .flex-auto.p-3.text-right
        = appliance.status

.mt-10
  = link_to 'Vissza', kitchens_path, class: "bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded"
  = link_to 'Hozzáadás', new_appliance_path(kitchen_id: @kitchen.id), class: "float-right bg-green-600 hover:bg-green-500 text-white font-bold py-2 px-4 rounded"