config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/auth/oauth/callback', to: 'sessions#create'


  resources :appliance_comments
  resources :appliances, only: %i[show new edit create update destroy]
  resources :kitchens
  resources :users, except: %i[new create destroy]

  post 'appliances/:id/', to: 'appliances#fire_transition', as: :fire_transition

  root 'kitchens#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.haml
#errors.bg-red-100.border.border-red-400.text-red-700.px-4.py-3.my-3.rounded.relative{:role => "alert"}
  %strong.font-bold
    = pluralize(errors.count, "error")
    prohibited this kitchen from being saved:
  %ul.pl-2
  - errors.full_messages.each do |message|
    %li= message
  %span.absolute.top-0.bottom-0.right-0.px-4.py-3
    %svg#close-errors.fill-current.h-6.w-6.text-red-500{:role => "button", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
      %title Close
      %path{:d => "M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"}

app/views/layouts/_nav.html.haml
.md:col-span-1.md:flex.md:justify-end.bg-white
  %nav.md:text-right.w-full
    .flex.justify-between.items-center.md:block.md:text-right
      %h1.font-bold.uppercase.p-4
        = link_to "KonyhaSCH", root_path, class: "hover:text-blue-700 tracking-widest"
      #burger.px-4.cursor-pointer.md:hidden
        %svg.w-6.h-6{:fill => "none", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24"}
          %path{:d => "M4 6h16M4 12h16M4 18h16"}
    %ul#menu.text-md.mt-1.px-4.pb-4.md:mt-4.md:p-0.hidden.md:block
      - navLinkClass = "block px-4 py-1 flex md:justify-end border-blue-300 border-l-4 md:border-l-0 md:border-r-4 transition duration-200 ease-in-out hover:text-blue-800 hover:bg-blue-100"
      %li.py-1
        = link_to "Konyhák", kitchens_path, class: navLinkClass
      %li.py-1
        = link_to "Friss jelentések", appliance_comments_path, class: navLinkClass
      - if policy(current_user).index?
        %li.py-1
          = link_to "Felhasználók", users_path, class: navLinkClass
      - if !logged_in?
        %li.py-4
          = link_to "AuthSCH bejelentkezés", login_path, class: navLinkClass
      - else
        %li.pt-4
          = link_to current_user.name ,user_path(current_user), class: "#{navLinkClass} font-bold"
        %li.py-1
          = link_to "Kijelentkezés" ,logout_path, class: navLinkClass

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}/
    %title Konyha
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.text-gray-700.flex.flex-col.md:grid.md:grid-cols-4.min-h-screen
    = render 'layouts/nav'

    - # container for right/main panel
    .md:col-span-3.bg-blue-100.flex-1.flex.flex-col

      - # notice box
      - if flash[:notice]
        #notice.mx-auto.my-4{:class => "w-5/6 md:w-2/3"}
          .bg-teal-100.border-t-4.border-teal-500.rounded-b.text-teal-900.px-4.py-3.shadow-md{:role => "alert"}
            %button#close-notice.bg-transparent.hover:bg-red-200.float-right.p-1.rounded
              %svg.fill-current.h-4.w-4.text-red-600{:role => "button", :viewbox => "2 2 16 16", :xmlns => "http://www.w3.org/2000/svg"}
                %title Bezárás
                %path{:d => "M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"}
            .flex
              .py-1
                %svg.fill-current.h-5.w-5.text-teal-500.mr-4{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
                  %path{:d => "M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"}
              %div
                %p.text-md= flash[:notice]

      %main.mx-6.my-6.md:mx-16.md:mt-10.md:mb-6.flex-1
        = yield

      %footer.mx-2.my-2.text-center
        %h5
          = link_to 'KonyhaSCH', 'https://github.com/kir-dev/konyha', class: 'no-underline hover:underline text-blue-500'
          © 2020
        %p
          Powered by
          = link_to 'Kir-Dev', 'https://kir-dev.sch.bme.hu/', class: 'no-underline hover:underline text-blue-500'

  = javascript_pack_tag 'main.js'
  = yield :scripts